alphanumeric_lowercase_only:
  - azurerm_analysis_services_server
  - azurerm_batch_account
  - azurerm_data_factory_linked_service_data_lake_storage_gen2
  - azurerm_data_lake_analytics_account
  - azurerm_data_lake_store
  - azurerm_data_share_dataset_kusto_cluster
  - azurerm_media_services_account
  - azurerm_storage_account

alphanumeric_only:
  - azurerm_app_service_certificate_order
  - azurerm_container_registry
  - azurerm_container_registry_webhook
  - azurerm_logic_app_integration_account
  - azurerm_frontdoor_firewall_policy
  - azurerm_storage_table

lowercase_only:
  - azurerm_container_group
  - azurerm_sql_failover_group
  - azurerm_sql_managed_instance
  - azurerm_sql_server
  - azurerm_service_fabric_cluster
  - azurerm_storage_container
  - azurerm_storage_queue
  - azurerm_storage_share

alphanumeric_underscore_only:
  - azurerm_disk_encryption_set

length_restricted:
  - azurerm_windows_virtual_machine
  - azurerm_windows_virtual_machine_scale_set